name: Fieldalignment

on: [pull_request]

jobs:
  fieldalignment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/src
    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Install Go 🗳
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Check if all struct fields are correctly aligned
      run: |
        go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
        fieldalignment "./..."
